In [22]:
# Bag of words,TFIDF, mACHINE LEARNING ALGORTHIMS

In [23]:
import pandas as pd
messages = pd.read_csv(r'N:\Personal_Projects\NLP\spam_classifier\SMSSpamCollection.txt', sep='\t', names= ["lable","message"])

In [24]:
messages

lable                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# Data Cleaning and Prprocessing

In [25]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nihar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [26]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [27]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

# Bag of Words

In [28]:
# create the bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=2500)

In [29]:
X    = cv.fit_transform(corpus).toarray()

In [30]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=10000,
                    formatter=dict(float=lambda x: "%.3g" % X))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [31]:
cv.vocabulary_

{'go': 804,
 'point': 1583,
 'crazi': 446,
 'avail': 141,
 'bugi': 274,
 'great': 828,
 'world': 2440,
 'la': 1086,
 'cine': 366,
 'got': 819,
 'wat': 2370,
 'ok': 1466,
 'lar': 1094,
 'joke': 1044,
 'wif': 2408,
 'oni': 1474,
 'free': 743,
 'entri': 612,
 'wkli': 2429,
 'comp': 401,
 'win': 2412,
 'fa': 655,
 'cup': 460,
 'final': 699,
 'tkt': 2215,
 'st': 2059,
 'may': 1254,
 'text': 2174,
 'receiv': 1738,
 'question': 1697,
 'std': 2070,
 'txt': 2272,
 'rate': 1717,
 'appli': 99,
 'dun': 574,
 'say': 1854,
 'earli': 578,
 'alreadi': 66,
 'nah': 1386,
 'think': 2189,
 'goe': 807,
 'usf': 2315,
 'live': 1153,
 'around': 114,
 'though': 2195,
 'freemsg': 745,
 'hey': 884,
 'darl': 479,
 'week': 2385,
 'word': 2437,
 'back': 154,
 'like': 1142,
 'fun': 763,
 'still': 2072,
 'tb': 2150,
 'xxx': 2468,
 'send': 1893,
 'rcv': 1720,
 'even': 626,
 'brother': 263,
 'speak': 2041,
 'treat': 2250,
 'per': 1535,
 'request': 1774,
 'mell': 1273,
 'oru': 1492,
 'minnaminungint': 1306,
 'nurungu': 

In [32]:
# output features
y = pd.get_dummies(messages['lable']).astype(int)
print(y.head())

   ham  spam
0    1     0
1    1     0
2    0     1
3    1     0
4    1     0


In [33]:
y.iloc[:,1].values

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [34]:
y=y.iloc[:,0].values


In [35]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [36]:
# Train-test splt
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y,test_size=0.20)

In [37]:
from sklearn.naive_bayes import MultinomialNB

In [39]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [40]:
spam_detect_model.predict(X_test)

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])